<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net472</TargetFramework>
    <LangVersion>10</LangVersion>
  </PropertyGroup>

  <PropertyGroup>
    <Description>Send OpenVR trackers over OSC</Description>
    <Company>milkydelta</Company>
    <Version>0.2.0</Version>
    <AssemblyName>openvr_osc</AssemblyName>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)' == 'Release'">
    <DebugType>none</DebugType>
  </PropertyGroup>

  <PropertyGroup>
    <DefineConstants>PCL,UNITY_5_3_OR_NEWER</DefineConstants>
  </PropertyGroup>


  <ItemGroup>
    <None Include="lib/libopenvr_api.so" Link="%(Filename)%(Extension)">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </None>
    <Content Include="lib/openvr_api.dll" Link="%(Filename)%(Extension)">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </Content>
    <Content Include="licenses/*">
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </Content>
    <Content Include="openvr_osc.sh">
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup Condition="'$(TargetFramework.TrimEnd(`0123456789`))' == 'net'">
    <Content Include="*.runtimeconfig.json">
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </Content>
  </ItemGroup>


  <!-- <ItemGroup>
    <PackageReference Include="Mono.Options" Version="6.12.0.148" />
  </ItemGroup> -->

</Project>